# Generated by Django 2.1 on 2018-08-22 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagemain', '0002_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileimage',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagemain.Topic'),
            preserve_default=False,
        ),
    ]
